USE alx_book_store;

SHOW CREATE TABLE books;
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'alx_book_store'
  AND TABLE_NAME = 'books'
  AND CONSTRAINT_NAME = 'PRIMARY';
